""" This tool is basically just a file opener. By using this you can open and read or write text in files. """

filename = input("Enter name of file : ")
print(" 1. If you wanna read file ")
print(" 2. If you want to write in file ")
print(" 3. If you want to erase all data in file ")
op = float(input(" >>> "))
if op ==  1 :
       file_opening = open(filename , "rb")
       print("Got your file.. ")
       print()
       for line in file_opening : print(line)
       print()
       print(" File ends here ! ")
       file_opening.close()
elif op == 2 :
       file_opening = open(filename , "w")
       print("Got your file ")
       print()
       print(" By default you can write 3 lines only ")
       line1 = input("Line 1. ")
       line2 = input("Line 2. ")
       line3 = input("Line 3. ")
       file_opening.write(line1)
       file_opening.write("\n")
       file_opening.write(line2)
       file_opening.write("\n")
       file_opening.write(line3)
       print(" Completed !! ")
       file_opening.close()
elif op == 3 :
       file_opening = open(filename , "w")
       file_opening.truncate()
       print(" Erased !!! ")
       file_opening.close()
else :
       print("Not valid option. choose 1 or 2 or 3 ")